### ISSUE TITLE
Detail Modal 기능 구현

### ISSUE THREAD

**Issue by swing-park** [swing-park/sidedish#28]
## Task

- [x] 메인 이미지와 일치하는 썸네일 이미지에 하이라이트 부여
- [x] 썸네일 이미지를 누르면, 메인 이미지가 변경되고 하이라이트도 변경
- [x] stock 초과 시 버튼 비활성화
- [x] 카운트에 따른 총 주문금액 변경
- [x] 주문하기 버튼 누를 시 주문 요청이 들어가고, 모달창이 close된다.

**Comment by swing-park** [comment]
완료
